# Generated by Django 6.0.4 on 2026-04-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_name', models.CharField(db_index=True, max_length=255)),
                ('path', models.TextField()),
                ('method', models.CharField(db_index=True, max_length=10)),
                ('requesting_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('status_code', models.PositiveSmallIntegerField(db_index=True)),
                ('is_error', models.BooleanField(db_index=True, default=False)),
                ('data', models.JSONField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'api_audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
